### ISSUE TITLE
Is this github repo abandoned?

### ISSUE THREAD

**Issue by erikkaplun** [pinard/Pymacs#1]
Should I still prefer http://pymacs.progiciels-bpi.ca/gitweb.cgi?p=pymacs;a=tree ?

**Comment by pinard** [comment]
I understand the confusion, sorry.  OK, I just changed the old Web pointers so they now point to GitHub.  And GitHub is now the proper place.  Thanks for the heads up.

**Comment by erikkaplun** [comment]
Oh, great, I just saw the HEAD of the old repo is still ahead of the GitHub repo, no?

**Comment by pinard** [comment]
Could it be only a question of branches?  "master" represents what has been published, while "dev-0.24" contains later commits.

Some script of mine, executed a few times per week, blindly mirrors my work repositories into GitHub, but I do not often login directly, and do not have much experience with it.  If you have suggestions about how I could better use GitHub, you are quite welcome to enlighten and educate me! :-)

Keep happy!

**Comment by erikkaplun** [comment]
I hope somebody will correct me if I'm wrong, but the master branch should reflect the latest work done and tags and other branches for other things, such as releases. At least this is how every other git repository works that I've seen :) Of course I'm no-one to say anything and things are OK as they are.

**Comment by erikkaplun** [comment]
Btw, I don't want to create another issue for this, but what's the (latest) version of Emacs that works fine with pymacs/ropemacs? I get random crashes with 23.2. I fixed it by adding a few lines to pymacs.py around line 327 in function free_python, but since I'm not an expert of the inner workings of neither Emacs nor Pymacs, I'm not sure if the patch was OK (in fact, I'm quite sure it wasn't, but at least it made ropemacs usable).

Oh and, btw, rope/ropemacs is an awesome thing! I appreciate the work you've done on it so much!

**Comment by pinard** [comment]
I do not mind much developping on "master" instead of "dev-0.24", this almost a non-issue — forgive me this little pun ☺  OK, I'll switch!  However, isn't the currently checked out branch the place where the latest developments occur?  If such always have to go on "master", then I probably miss what I thought to be the main purpose of branches!  (You may use mailto:pinard@iro.umontreal.ca if you feel that we continue this more privately, but either way, that's OK with me.)

**Comment by erikkaplun** [comment]
master is the default branch every git repo has (or should have), and what I meant is that the main development line should take place in master. (Other) branches are for parallel development stuff, experimental stuff, temporary stuff etc.
Basically it's just that when somebody visits your github page, they probably expect to see the latest code in master, that's all... unless you want to confuse them :)

**Comment by pinard** [comment]
About the latest version of Emacs that works with Pymacs/ropemacs, I do not know.  I'm using Pymacs with Emacs 23.1 here, and have no problem, but I use Pymacs in rather humble ways, and might not be a representative user.  You might want to raise the same question on the pymacs-devel@googlegroups.com mailing list?  There might be more serious Pymacs users in there! ☺

**Comment by erikkaplun** [comment]
Oh, great, but you still are they main/lead developer, right?

**Comment by pinard** [comment]
"dev-0.24" has been deleted, and "master" replaces it.  Thanks for the suggestion, and the discussion.

I do not commit often, I guess I'm still the main commiter.  The project might be forked, of course, that's a free world.  I surely like Pymacs to stay simple and quiet, without bloat nor bugs.

**Comment by erikkaplun** [comment]
That's great, thanks :) Maybe if people find out there's a github repository, they will start forking off of it, and you'll be able to track everything :)
