### ISSUE TITLE
Add autoload cookies

### ISSUE THREAD

**Issue by leoliu** [pinard/Pymacs#10]
Add autoload cookies so that they can be generated automatically.

Patch: http://paste.pound-python.org/raw/15513

**Comment by pinard** [comment]
Hello, happily applied locally, thanks!  Please tell me your real name (and your home Web page if any).

Now, I'm ignorant, please educate me.  While I see those autoload cookies here and there, I do not know how they get activated.  I thought there were only meant for packages included in the standard Emacs distribution and installed with it.  I did not think Pymacs has to do something about it.

François

**Comment by leoliu** [comment]
Thank you for adding it.

Users can M-x update-directory-autoloads to update an autoload file. So with this change, one can easily drop the file in that directory and update the autoload file and have pymacs lazily loaded.

My real name: Leo Liu @ https://github.com/leoliu
