### ISSUE TITLE
Pymacs Lisp version computability problem

### ISSUE THREAD

**Issue by khajavi** [pinard/Pymacs#12]
I have installed rope, ropemacs, ropemode and Pymacs. and my .emacs.el is:

(require 'pymacs)
(pymacs-load "ropemacs" "rope-")

when I start emacs --debug-init this error occur:

Debugger entered--Lisp error: (error "Pymacs Lisp version is 0.23, Python is 0.24-beta2")
  signal(error ("Pymacs Lisp version is 0.23, Python is 0.24-beta2"))
  pymacs-report-error("Pymacs Lisp version is 0.23, Python is %s" "0.24-beta2")
  pymacs-start-services()
  pymacs-serve-until-reply("eval" (pymacs-print-for-apply (quote "pymacs_load_helper") (quote ("ropemacs" "rope-"))))
  pymacs-call("pymacs_load_helper" "ropemacs" "rope-")
  pymacs-load("ropemacs" "rope-")
  eval-buffer(#<buffer  *load*> nil "/home/milad/.emacs.el" nil t)  ; Reading at buffer position 769
  load-with-code-conversion("/home/milad/.emacs.el" "/home/milad/.emacs.el" t t)
  load("~/.emacs" t t)
  #[nil "^H\205\264^@   \306=\203^Q^@\307^H\310Q\2027^@ \311=\2033^@\312\307\313\314#\203#^@\315\2027^@\312\307\313\316#\203$
  command-line()
  normal-top-level()

**Comment by pinard** [comment]
khajavi
reply@reply.github.com
writes:

> Debugger entered--Lisp error: (error "Pymacs Lisp version is 0.23,
> Python is 0.24-beta2")

Hello, khajavi.  Is that your name?  Your email had no signature.

As the diagnostic suggests, the Lisp part comes from the version 0.23 of
Pymacs, the Python part comes from 0.24-beta2.  You have to make sure to
use both parts from the same distribution.

It might help to delete files coming from 0.23 (or move them out of the
way), so removing the confusion between versions.

François

**Comment by khajavi** [comment]
Hi François,

My name is Milad, and Khajavi is my last name. for signature is it
sufficient to insert my name at the end of letter?
Regard to your help, I removed Pymacs that come from my distribution: sudo
apt-get remove pymacs
Then I get pymacs from github and insert it in my ~/.emacs.d/ directory
then I added this line in my .emac.el:
(add-to-list 'load-path "~/.emacs.d/Pymacs")
now I ropemacs work successfully with pymacs.

Milad (Nice? :D)

On Monday, December 26, 2011, François Pinard <
reply@reply.github.com>
wrote:

> khajavi
> reply@reply.github.com
> writes:
> 
> > Debugger entered--Lisp error: (error "Pymacs Lisp version is 0.23,
> > Python is 0.24-beta2")
> 
> Hello, khajavi.  Is that your name?  Your email had no signature.
> 
> As the diagnostic suggests, the Lisp part comes from the version 0.23 of
> Pymacs, the Python part comes from 0.24-beta2.  You have to make sure to
> use both parts from the same distribution.
> 
> It might help to delete files coming from 0.23 (or move them out of the
> way), so removing the confusion between versions.
> 
> François
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pinard/Pymacs/issues/12#issuecomment-3275985

## 

﻿﻿Milad Khajavi
http://lincafe.wordpress.com
Having the source means you can do it yourself.
I tried to change the world, but I couldn’t find the source code.

**Comment by pinard** [comment]
Hi, Milad! :-)

> now I ropemacs work successfully with pymacs.

Congratulations!  Have fun!

François
