### ISSUE TITLE
Allow changing pymacs-load-path at run-time

### ISSUE THREAD

**Issue by leoliu** [pinard/Pymacs#19]
Patch in: http://paste.pocoo.org/raw/eFkbZaoaO2mO14KwJSIr/

**Comment by pinard** [comment]
leoliu
reply@reply.github.com
writes:

> Patch in: http://paste.pocoo.org/raw/eFkbZaoaO2mO14KwJSIr/

Hi, Leo.

I see the patch.  For this one, I wonder what is the real need behind
it.  I try to only put in Pymacs features which are blatantly useful.

Would you be kind enough to describe the actual situation which
triggered you into writing this code?  It surely happened that I had to
change pymacs-load-path, but it occurred so exceptionally that it was
not a problem at all for me to restart Emacs.

It seems that you hit a natural case in which you need to change the
path on the fly, and for which it would be really inappropriate to
restart Emacs or Pymacs; that is, a case in which some application may
not be stopped.  I'm curious to know and understand more about it.

François

**Comment by leoliu** [comment]
I have been thinking about integrating pymacs into emacs system-wide for example, setup pymacs in site-start.el and possibly make some system-wide python extensions available. It is all good except for the non-admin users since they cannot change site-start.el. There is need for them to have their own python extensions located in a path they choose. But by the time they started emacs, pymacs will have been loaded by the system-wide setup.

My patch just makes it easier for users to customise pymacs-load-path even if the admin of an operating system has loaded pymacs in site-start.el.

**Comment by leoliu** [comment]
I did some experiment last night and it seems this patch is not necessary. So I am closing the issue. Sorry for the noise.
