### ISSUE TITLE
pymacs-load-history

### ISSUE THREAD

**Issue by leoliu** [pinard/Pymacs#24]
I remembered when first tried out pymacs I was asked this question: Killing the Pymacs helper might create zombie objects. To be honest even today I have only vague idea what it is.

So I just started using something in this patch: https://gist.github.com/2576300 and find it to be useful. It turns out it will capture most important things users care about. I haven't tested it thoroughly but posted here so that I can have input from other than myself.

Thanks.
Leo

**Comment by tkf** [comment]
+1 for adding `pymacs-load-history`.  I have similar in my Emacs setting using defadvice and it is very useful.

**Comment by pinard** [comment]
Hello, Leo.  Sounds interesting indeed.  Let me release Pymacs now, and consider your suggestion next.

**Comment by pinard** [comment]
Hi, Leo.

Would you apply this patch to your own fork of Pymacs, then send a pull request?  This is just so to mark you as the commiter.  Absolutely no problem if you do not feel like doing so, I'll then merely apply the patch myself.

François

**Comment by leoliu** [comment]
Just did it. My first time using the pull requests feature in github.

**Comment by leoliu** [comment]
Not related to the topic at hand.

I wonder if the following tweak is good to have: https://github.com/leoliu/Pymacs/commit/9828d798a6049985258855b95c065d8de28b3171

**Comment by pinard** [comment]
Hi, Leo.  I'm not finding how to automatically apply the commit above (if you happen to know, tell me of course!).  If you do a pull request out of it, I know how :-).  Make on, if it does not bother you too much.  In the meantime, I'll try fetching your own Pymacs fork into mine at home, do the cherry pick locally and push it back to GitHub afterwards.  Normally, accepting your pull request on GitHubthen should then be a no-operation, and that's I would like to test.

**Comment by pinard** [comment]
Done here, for your commit 9828d.  Thanks!

**Comment by leoliu** [comment]
Thanks and sorry for the inconvenience.

**Comment by pinard** [comment]
Inconvenience?  None at all!  You're a nice collaborator, Leo, never think nothing less of yourself!  Thanks
