### ISSUE TITLE
Write homebrew formula

### ISSUE THREAD

**Issue by dicato** [pinard/Pymacs#25]
Pymacs is in macports, but not homebrew. 
Do you have any qualms about it being included in homebrew? 

I suspect they will say it belongs in pypi, and after reading the snippet in your README, I really don't know. I think whatever enables people to use Pymacs is better.

**Comment by pinard** [comment]
Hello!

Surely no problem with me.  Moreover, Pymacs is free software!  Do you see any reason why I should be cautious?

Maybe a year ago, I had the opportunity of using an iMac for a week or two, and for the little I know of it, I found homebrew to be nice and useful! :-).

François

**Comment by dicato** [comment]
To get it into homebrew requires a good explanation of why it is not in pypi (or elsewhere). From your readme it sounds like there is mutual exclusion in emacs and python packagers, making neither of them very suitable. It seems that using a third party packager like homebrew is a potential solution. IMO, all generic package managers (apt, yum, macports, homebrew) have their problems, but the occasional annoyance is better than rolling everything yourself. 

I've blindly used pymacs via macports for awhile, so I never looked into the requirements and installer. I used it as part of http://gabrielelanaro.github.com/emacs-for-python/. I'll take a stab at writing a homebrew formula and link it here when it's done. Not sure when.

**Comment by pinard** [comment]
Hi again!

When you write "neither of them very suitable", I would say "both are needed". :-)

We started rather recently to look at packagers.  Pymacs is now in good shape for ELPA's on the Emacs Lisp side.  The next step is to look for a packager on the Python side, and it might be "packaging", standard in Python3,  itself backported as an optional "distutils2" in Python2.  pip and others are meant to be reoriented towards "packaging".  The insertion of Pymacs into Python packagers is likely to happen soon, but I'm not giving dates nor making promises.

But right now, indeed, you have "a good explanation" if you need one.  Would Pymacs have to be removed from homebrew if it becomes available through installers?  If yes, it might not be worth the effort of putting it in then.  You judge.  Whatever you do, keep me informed, so I could in turn keep Pymacs users informed.  Thanks, and keep happy!

François

P.S. You may visit issues #18 and #21 for more comments on packaging.

**Comment by dicato** [comment]
I actually was browsing #18 and just commented. 

You got it write, both are needed. Homebrew will most likely reject it. They have nice utilities for creating a "formula" so I only invested 10 minutes. With my emacs-for-python installation, it worked perfect. If you end up having to look at other package managers, this does work as an option.
