### ISSUE TITLE
installation doesn't work for python 2.7

### ISSUE THREAD

**Issue by xdong** [pinard/Pymacs#28]
I tried to run make (or make install) but nothing happened (nothing got built). BTW I can install Pymacs 0.24beta2.

~/Downloads/pinard-Pymacs-8b435ce$ make
python pppp -C ppppconfig.py Pymacs.py.in pppp.rst.in pymacs.el.in pymacs.rst.in contrib tests
python setup.py --quiet build
~/Downloads/pinard-Pymacs-8b435ce$ ls
contrib   ppppconfig.py  pymacs.el.in  pymacs.rst.in  setup.py
COPYING   pppp.rst       Pymacs.py     pymacs.wpr     tests
Makefile  pppp.rst.in    Pymacs.py.in  README.md      THANKS
pppp      pymacs.el      pymacs.rst    setup.cfg      TODO

**Comment by leoliu** [comment]
I think I have this similar problem. But I use pip and it only installs auxiliary files. I have to manually copy Pymacs.py over.

**Comment by xdong** [comment]
It turned out that the problem for me (in Linux) was that I had set the environment variable LANG=C. Once I changed it to the default LANG=en_US.UTF-8 the installation worked fine.

I don't fully understand why though.
