### ISSUE TITLE
Improve pymacs-load's error report

### ISSUE THREAD

**Issue by leoliu** [pinard/Pymacs#30]
Hello François,

I wonder if you may review (and if useful merge) this commit:
https://github.com/leoliu/Pymacs/commit/63b180a2440ad6198056ec140556f30dfb50e817

I tested it with python 2.7.3 and seemed to work.

Leo

**Comment by leoliu** [comment]
Any comments on this patch? Thanks.

**Comment by pinard** [comment]
Good idea, Leo.  Done! :-)
