### ISSUE TITLE
make check fails on MacOS 10.6.6 with emacs 24.0.50 from bzr trunk

### ISSUE THREAD

**Issue by lotia** [pinard/Pymacs#4]
Hello,
I'm attempting to set up Pymacs on my Mac OS 10.6.6 machine and ran make check before attempting an install. make check gets stuck when running t31_elfile_works.py

I am running emacs 24.0.50 compiled locally from a clone of the bzr trunk. The version info of the tip is:
revno: 103416
revision-id: rgm@gnu.org-20110224084525-s63pp76gna3g61yt

The output I receive when running make check is:
aal-i5-mbp:Pymacs lotia$ make check
rm -f tests/debug-protocol tests/debug-signals
python pppp -C ppppconfig.py pymacs.el.in Pymacs tests
cd tests && \
      EMACS="emacs" PYTHON="python" \
      PYMACS_OPTIONS="-d debug-protocol -s debug-signals" \
      python pytest -f t 
./t01_pppp_works.py ···························································
   60 ·············· (73)
./t10_pyfile_loads.py · (1)
./t11_pyfile_works.py ·························································
   58 ··································· (92)
./t20_helper_loads.py · (1)
./t21_helper_works.py ··············································· (47)
./t30_elfile_loads.py · (1)
./t31_elfile_works.py ·························································
   58 ·····························

it stops at the same point each time.

I'm new to Python so I'm afraid this issue report isn't accompanied with a patch.

**Comment by pinard** [comment]
You do not have to provide a patch.  I may sometimes hope patches from someone asing for unsupported or new features (however, sending a patch is no guarantee that I'll like the feature! ☺).

Here, I do not know much what to do, as I do not have access to such a machine.  We might organize a debugging session over Skype, or something, maybe?  But we'll have to find a time when we are both available, and I would likely suggest that you use a recent checkout of the code, so we use the same base.  Email me directly in case you think it might help.

**Comment by pinard** [comment]
I may not do much about this report, and the original submitter did not follow up.  I confess I was not too fast myself, sigh!

Let's be practical, I'll close this issue as well.  If you, or someone, feel like contacting me so we can organize some testing on systems like this one, for which I do not have easy access, just reopen this issue, or otherwise contact me, and we'll try to find some way.
