### ISSUE TITLE
Minor fix to pymacs-terminate-services

### ISSUE THREAD

**Issue by leoliu** [pinard/Pymacs#42]
I accidentally killed the _Pymacs_ and after that pymacs behaved weirdly. It seems the following patch is needed for pymacs to clean up properly.

```
diff --git a/pymacs.el.in b/pymacs.el.in
index 0c14fd81..97fa4b40 100644
--- a/pymacs.el.in
+++ b/pymacs.el.in
@@ -685,7 +685,7 @@ Killing the Pymacs helper might create zombie objects.  Kill? "))
            (remove-hook 'post-gc-hook 'pymacs-schedule-gc))
           ((pymacs-timerp pymacs-gc-timer)
            (pymacs-cancel-timer pymacs-gc-timer)))
-    (when pymacs-transit-buffer
+    (when (buffer-live-p pymacs-transit-buffer)
       (kill-buffer pymacs-transit-buffer))
     (setq pymacs-gc-inhibit nil
           pymacs-gc-timer nil
```

**Comment by pinard** [comment]
Hello, Leo.

This patch is not likely _needed_, as the function pymacs-terminate-services is not called; it is only provided for documentation purposes.  Nevertheless, your suggestion is good (as usual from you ☺), so I'm putting it in.  Moreover, there are other places when the same modification might be welcome, so I do thank you for catching this issue!

François (who is wishing you a Nice Year!)

P.S. Well, I see from the documentation that (buffer-name BUFFER) returns nil for a buffer which has been killed, so (buffer-live-p BUFFER) is not that required, after all.  The problem might lie elsewhere, then.

**Comment by leoliu** [comment]
Hello François,

Thanks for closing this issue and my belated happy new year!

Leo
