### ISSUE TITLE
Any idea what would be causing Pymacs to be slow on Snow Leopard OSX?

### ISSUE THREAD

**Issue by milkypostman** [pinard/Pymacs#5]
I haven't tried compiling my own version of Python yet, although I'm close to doing so, but it seems like using ropemacs with pymacs is very slow.  There are numerous people who use ropemacs for autocompletion but I cannot do so.  It's just too painfully slow.

Possibly this is a problem with rope but there is at least one more person with this issue:
http://groups.google.com/group/gnu.emacs.help/browse_thread/thread/ca15f5d465a9da23

I'm not sure how to test what is going on or where the slowdown is.  My hunch is that it _is_ rope and simply something on OSX is slowing rope down.

**Comment by ghost** [comment]
My Pymacs is very very slow on Snow Leopard, why?

**Comment by simao** [comment]
I also have the same problem.
Any luck with this?

**Comment by milkypostman** [comment]
I didn't.  I just kinda stopped using it.  Maybe it's better on Lion?  I haven't tried.

Please let me know if you get it going, it'd be nice to know.

**Comment by trjordan** [comment]
I've been having the same problem -- 10 or 15 seconds to find a set of occurrences inside a moderately sized repo.

My suspicion is that it's Pymacs -- I've narrowed down one bottleneck to the `_save_buffers` file in ropemode's interface.py.

For reference: 

```
def _save_buffers(self, only_current=False):
    if only_current:
        filenames = [self.env.filename()]
    else:
        filenames = self.env.filenames()
    pythons = []

    # Added by me for debugging 
    self.env._make_buffer('*ropefiles*', '\n'.join(filenames))
    return

    for filename in filenames:
        if self._is_python_file(filename):
            pythons.append(filename)
    self.env.save_files(pythons)
```

Returning before the self.env.filenames call is fine and zippy, afterwards is 5 seconds or so. All that function does is build a list of buffers from buffer-list and buffer-file-name -- the equivalent elisp looks like it would be:

```

(let (value) 
     (dolist (elt (buffer-list) value) 
     (let ((filename (buffer-file-name elt)))
     (if filename (setq value (cons filename value))))))
```

which runs immediately. 

So, it seems to me like there's something up with Pymacs. I'm going to keep poking at it, but any help would be appreciated. 

(Also, FWIW, I'm running Lion)

**Comment by pinard** [comment]
I've not much to say, let me try a bit nevertheless.

Pymacs is not necessarily fast, as Emacs and Python are communicating with each other over pipes.  This is quite different from Python in Vim, say, where Python is _built_ within, with more intimate and immediate communication.  You might get hints about where slowness occurs by monitoring the _Pymacs_ buffer within Emacs (see the Pymacs documentation about how to set its size and shrink threshold).

In my own Pymacs applications, it happened that bits of Emacs Lisp code sped up things tremendously.

Do you see what else I could do about it?  If no comments in a week or too, I'll close this issue, I guess.

**Comment by trjordan** [comment]
(You'll have to excuse my previous post -- it was too late, and I was a bit mixed up about which repo I was complaining about.)

Anyway, I don't think Pymacs is to blame here, at least for me. I've subsequently noticed rope is slow from the command line as well, on both OS X and Lion. It's just getting a list of all file names and grepping/intepreting/matching each one. On the repo I'm working on, that's a fair amount of work. So, I don't use those functions.

So ... I'm not sure. Perhaps having less of ropemacs built in Pymacs would be better, but that's a bigger project than seems worth it at this point. In any case, thanks for the reply.

**Comment by simao** [comment]
I understand that Pymacs is not fast, but it's basically unusable in my OS X installation. Maybe @trjordan is right and it's rope that isn't working properly, maybe it's something else, but I simply can't use rope/pymacs.

Also, I have this problem even when using just a single python file, so I don't think this is related to the size of the project.

How could I debug this? Checking the Pymacs buffer? I'll try to adjust those parameters.

Thanks!

**Comment by pinard** [comment]
Hi again!

Oh, sorry, I might have sent false hopes.  _Adjusting those parameters_ is not going to give you any speed, but merely allow you to observe a bit more what is going on between Emacs and Python.  You see requests and replies as they go between both processes.  So, if you see some unusual, suspicious delay between a given request and its reply, by looking at the request or the reply contents, and given enough luck, you might develop a feel or hint about a possible problem.  So no promise!

In particular, if requests and replies flow all regularly, but all slowly, you are not getting any hint I presume.

**Comment by pinard** [comment]
Out of despair, you can check this article: [Daniel Fischer's Blog - Wow, I just found a major performance bug in OSX.](http://blog.danielfischer.com/2011/10/20/wow-i-just-found-a-major-performance-bug-in-osx/) .  Who knows! :-)

**Comment by leoliu** [comment]
There is a bug in the ns-port of Emacs regarding communication to external processes. (See: http://debbugs.gnu.org/2056). To check this, try building emacs without ns on OSX. I would recommend anybody whose productivity has been halved by this bug to write more bug reports so that the developers know that it is serious:

  M-x report-emacs-bug

**Comment by pinard** [comment]
For this problem as well, I feel powerless, and have no better advice to give.  It might be a Ropemacs problem, or maybe Rope relying too much on Pymacs?  I do not like always pointing at Rope, knowing that Pymacs is far from perfect :-).

I'll close this issue.  Presumably (I'm not _that_ familiar with GitHub), closing will not prevent further discussions if anybody has more information or some clue about how to ease people out of this problem.

François

**Comment by milkypostman** [comment]
Sounds good. I haven't dug into this any further lately.
