### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by ericpar** [pinard/Pymacs#54]
Hi,

The hyperlinks to the [PDF](http://pymacs.progiciels-bpi.ca/pymacs.pdf) and [HTML](http://pymacs.progiciels-bpi.ca/pymacs.html) documentation are broken as of 2013-09-24.

Can I get them elsewhere?

Regards,

Eric

**Comment by pinard** [comment]
Hi, Eric.  I recently shuffled a lot of files around, and my various Web sites need some love.  I'll try to address them all today, or at least, soon.  I'm currently on sick leave, and need to take care of myself first! :-).  Email to me privately (pinard@iro.umontreal.ca) if you are in a hurry, I'll send them to you directly.  Keep happy.  François

**Comment by pinard** [comment]
Hi again.  Both links above should be repaired.  I also saw other details to repair on that site, things might stay a bit flaky while I test and tune the generating machinery.  Thanks for the report!  François
