### ISSUE TITLE
Symbol's value as variable is void: @DEFADVICE_OK@

### ISSUE THREAD

**Issue by ghost** [pinard/Pymacs#6]
i use pymacs in windows 7, i just copied pymacs.el.in.  Typed "M-x pymacs-eval RET"  then i got this error!

**Comment by pinard** [comment]
Le 2011-08-25 11:02, lZZZl a écrit :

> i use pymacs in windows 7, i just copied pymacs.el.in.  Typed "M-x pymacs-eval RET"  then i got this error!

It looks like Pymacs was not fully installed.  Sometimes, on Windows,
people lack tools like Make, or a shell, and then install "by hand" and
forget some installation steps.  I guess this is the problem. One need
to do:

python pppp -C ppppconfig.py *.in Pymacs contrib tests
python setup.py install

eventually replacing *.in par the extended list, which is (here):

pppp.rst.in pymacs.el.in pymacs.rst.in

Hopefully, these steps should get you going.

Keep happy!  François

**Comment by pinard** [comment]
Le 2011-08-25 11:02, lZZZl a écrit :

> i use pymacs in windows 7, i just copied pymacs.el.in.  Typed "M-x pymacs-eval RET"  then i got this error!

Sorry, I forgot to say: don't use pymacs.el.in, but the pymacs.el
resulting from the execution of pppp.

François

**Comment by ghost** [comment]
Thanks your reply! I did it as you say, but got a new error below：

C:\Users\lZl\Desktop\pinard-Pymacs>python p4 -C p4config.py _.in Pymacs contrib tests
Traceback (most recent call last):
  File "p4", line 421, in <module>
    main(_sys.argv[1:])
  File "p4", line 124, in main
    self.transform_all_files(argument)
  File "p4", line 241, in transform_all_files
    input, open(input), open(output, 'w').write)
IOError: [Errno 22] invalid mode ('r') or filename: '*.in'

thanks again!

**Comment by pinard** [comment]
Le 2011-08-25 12:27, lZZZl a écrit :

> Thanks your reply! I did it as you say, but got a new error below：
> 
> C:\Users\lZl\Desktop\pinard-Pymacs>python p4 -C p4config.py _.in Pymacs contrib tests
> Traceback (most recent call last):
>   File "p4", line 421, in <module>
>     main(_sys.argv[1:])
>   File "p4", line 124, in main
>     self.transform_all_files(argument)
>   File "p4", line 241, in transform_all_files
>     input, open(input), open(output, 'w').write)
> IOError: [Errno 22] invalid mode ('r') or filename: '*.in'
> 
> thanks again!

Hi again.  I might have explained myself poorly.  If your shell does not
expand *.in, you have to do it "by hand", and write

python pppp -C ppppconfig.py pppp.rst.in  pymacs.el.in  pymacs.rst.in
Pymacs contrib tests

(on one line), then:

python setup.py install

You might also want to peruse pymacs.rst (or pymacs.rst.in if you did
not execute the pppp step yet) for more information, yet admittedly,
there is a lot to read in there.  Good luck with the installation.

François

**Comment by ghost** [comment]
it works!
i'm sorry about my fool mistake！
Thanks a lot :)

**Comment by pinard** [comment]
Le 2011-08-25 12:49, lZZZl a écrit :

> it works!
> Thanks a lot :)

Have fun! :-)

**Comment by eric-p** [comment]
Hi, 
I have the exact same problem.
Plus  the command :

> python pppp -C ppppconfig.py pppp.rst.in pymacs.el.in pymacs.rst.in Pymacs contrib tests
> gave me : 
> - Pymacs does not end with .in, ignored.

so I tried :

> python pppp -C ppppconfig.py pppp.rst.in pymacs.el.in pymacs.rst.in Pymacs.py.in contrib tests

and it seemed to work. : 

> python setup.py install
> running install
> running build
> running build_py
> running install_lib
> running install_egg_info
> Removing c:\python27\Lib\site-packages\Pymacs-0.24_beta2-py2.7.egg-info
> Writing c:\python27\Lib\site-packages\Pymacs-0.24_beta2-py2.7.egg-info

then :

> python
> Python 2.7.1 (r271:86832, Nov 27 2010, 18:30:46) [MSC v.1500 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > from Pymacs import lisp

No error, so it seems OK.
Then I copied the generated pymacs.el to c:\programs\emacs-23.4\site-lisp,
put the lines:
(autoload 'pymacs-apply "pymacs")
(autoload 'pymacs-call "pymacs")
(autoload 'pymacs-eval "pymacs" nil t)
(autoload 'pymacs-exec "pymacs" nil t)
(autoload 'pymacs-load "pymacs" nil t)
(autoload 'pymacs-autoload "pymacs")
;;(eval-after-load "pymacs"
;;  '(add-to-list 'pymacs-load-path YOUR-PYMACS-DIRECTORY"))
into _emacs in my HOME directory, 
and started emacs.
Again, "M-x pymacs-eval RET" gives the message : Symbol's value as variable is void: @DEFADVICE_OK@

If I load the pymacs libarary, I get the same message. I can't see what I missed. There has to be something...
Any idea ?
PS : this is worse than 7, it is Vista.
I'll try again on an XP box tonight...
Best regards,
Éric

**Comment by pinard** [comment]
Thanks for the correction, I just replaced Pymacs by Pymacs.py.in at the appropriate place in the documentation.

Check that ppppconfig.py does define DEFADVICE_OK to something sensible (normally t).  Make sure that after the pppp call, no @DEFADVICE_OK@ remain in the resulting pymacs.el.  If there is, we have a problem to solve right there.  If everything is OK there, then maybe you are not loading the pymacs.el file you think you are loading, so make sure you get rid of any old copy that might be floating around from some previous installation.

Tell me how it goes, and good luck.  François
