### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [pinard/Pymacs#66]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine setup.py and observe `dictionnary`, however expect to see `dictionary`.
- Examine contrib/Giorgi/tester.py and observe `completition`, however expect to see `completion`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/Pymacs/pull/new/bugfix_typos

Thanks.

**Comment by punchagan** [comment]
@timgates42 https://github.com/dgentry/Pymacs is where the development of Pymacs happens now.
